name: mobile_app
description: "Mobile platform for TripConnect ecosystem."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0
  http: ^1.2.2
  provider: ^6.0.5
  flutter_localization: ^0.2.1
  cupertino_icons: ^1.0.6
  loading_animation_widget: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/app-background.jpg
  - assets/images/google-logo.png
  fonts:
  - family: inter
    fonts:
    - asset: assets/fonts/inter/standard.ttf